apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {name}
  name: {name}
  namespace: {namespace}
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - {start-up-command}
    image: {image}
    imagePullPolicy: Always
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/bash
          - -c
          - {post-start-command}
    name: container-0
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "16"
        memory: 32Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: Default
  imagePullSecrets:
  - name: imagepull-secret
  restartPolicy: Always
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
  nodeSelector:
    node.cci.io/allowed-on-poc-dedicated-node: sina
  tolerations:
  - effect: NoSchedule
    key: node.cci.io/allowed-on-poc-dedicated-node
    operator: Equal
    value: sina
